import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

  <nav className="bg-white px-8 py-5 flex justify-center gap-8 shadow-sm">

   <a href="/" className="font-bold">
  首页
</a>

<a href="/daily" className="font-bold">
  每日记录
</a>

<a href="/dance" className="font-bold">
  舞蹈记录
</a>

<a href="/colors" className="font-bold">
  色彩档案
</a> 

  </nav>


    
{children}


<footer className="mt-auto bg-[#FFF9EE] py-10 text-center text-[#5A4636]">

  <p className="font-bold text-lg">
    🌻 KUIKUIZI Daily Archive
  </p>

  

 <div className="mt-6 max-w-md mx-auto px-6">

  <p className="leading-relaxed">
    用心记录每一个关于葵葵子的瞬间，
    <br />
    收藏那些闪闪发光的日子。
  </p>

  

  <p className="mt-5 font-bold">
    —— NiyaraZ
  </p>

</div>


  <p className="mt-8 text-xs opacity-50">
    Created by NiyaraZ
    <br />
    A little archive filled with love for KUIKUIZI 🌻
    <br />
    © 2026 KUIKUIZI Daily Archive
  </p>


</footer>
 

</body>
    </html>
  );
}
